%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.18.9 on {{2015,11,24},{13,10,44}}

-ifndef(textsecure).
-define(textsecure, true).

-define(textsecure_gpb_version, "3.18.9").

-record(sender_key_message,
        {id,                            % = 1, uint32 (optional)
         iteration,                     % = 2, uint32 (optional)
         ciphertext                     % = 3, bytes (optional)
        }).

-record(key_exchange_message,
        {id,                            % = 1, uint32 (optional)
         baseKey,                       % = 2, bytes (optional)
         ratchetKey,                    % = 3, bytes (optional)
         identityKey,                   % = 4, bytes (optional)
         baseKeySignature               % = 5, bytes (optional)
        }).

-record(prekey_whisper_message,
        {registrationId,                % = 5, uint32 (optional)
         preKeyId,                      % = 1, uint32 (optional)
         signedPreKeyId,                % = 6, uint32 (optional)
         baseKey,                       % = 2, bytes (optional)
         identityKey,                   % = 3, bytes (optional)
         message                        % = 4, bytes (optional)
        }).

-record(whisper_message,
        {ratchetKey,                    % = 1, bytes (optional)
         counter,                       % = 2, uint32 (optional)
         previousCounter,               % = 3, uint32 (optional)
         ciphertext                     % = 4, bytes (optional)
        }).

-record(sender_key_distribution_message,
        {id,                            % = 1, uint32 (optional)
         iteration,                     % = 2, uint32 (optional)
         chainKey,                      % = 3, bytes (optional)
         signingKey                     % = 4, bytes (optional)
        }).

-endif.
