%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.8.0

-ifndef(textsecure).
-define(textsecure, true).

-define(textsecure_gpb_version, "4.8.0").

-ifndef('WHISPER_MESSAGE_PB_H').
-define('WHISPER_MESSAGE_PB_H', true).
-record(whisper_message,
        {ratchetKey             :: iodata() | undefined, % = 1
         counter                :: non_neg_integer() | undefined, % = 2, 32 bits
         previousCounter        :: non_neg_integer() | undefined, % = 3, 32 bits
         ciphertext             :: iodata() | undefined % = 4
        }).
-endif.

-ifndef('PREKEY_WHISPER_MESSAGE_PB_H').
-define('PREKEY_WHISPER_MESSAGE_PB_H', true).
-record(prekey_whisper_message,
        {registrationId         :: non_neg_integer() | undefined, % = 5, 32 bits
         preKeyId               :: non_neg_integer() | undefined, % = 1, 32 bits
         signedPreKeyId         :: non_neg_integer() | undefined, % = 6, 32 bits
         baseKey                :: iodata() | undefined, % = 2
         identityKey            :: iodata() | undefined, % = 3
         message                :: iodata() | undefined % = 4
        }).
-endif.

-ifndef('KEY_EXCHANGE_MESSAGE_PB_H').
-define('KEY_EXCHANGE_MESSAGE_PB_H', true).
-record(key_exchange_message,
        {id                     :: non_neg_integer() | undefined, % = 1, 32 bits
         baseKey                :: iodata() | undefined, % = 2
         ratchetKey             :: iodata() | undefined, % = 3
         identityKey            :: iodata() | undefined, % = 4
         baseKeySignature       :: iodata() | undefined % = 5
        }).
-endif.

-endif.
